<!-- 
www.vnlisting.com
Online Super Bowl Squares Script
Please read the "Readme.txt for license agreement, installation and usage instructions 
-->

<!-- You may not and shall not make any changes to this file -->
<p>
<table width="95%" style="font-family: verdana, arial; font-size: 9px">
<tr>
<td>Copyright &copy; 2004-<?=date("Y")?> <a href="http://www.vnlisting.com/freescripts.php" title="Vietnamese Business Directory" target="_parent">VNLISTING</a></td>
<td align="right"><a href="http://www.vnlisting.com/freescripts.php" title="Download & Support" target="_parent">VNSB Squares <?=$VERSION?></a></td>
</tr>
</table>
</p>
</center>
<?php mysql_close($db);	?>
</body>
</html>